on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.4
      - name: hello
        run: echo ${{toJSON(github)}}
      - name: Hello world action step
        id: hello
        uses: ./.github/actions/hello-world-docker-action
        with:
          who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
        
      - name: add a file
        run: echo hello > hello.txt
      
      - name: uploadtest
        uses: actions/upload-artifact@v2
        with:
           name: my-artifact
           path: hello.txt
